#!/bin/bash

fixdirs () {
    find $1 -type d -print0 | xargs -0 chmod 0775
    find $1 -type f -print0 | xargs -0 chmod 0664
}

if [ ! -x "$(command -v find)" ]; then
    echo "Error: find is not installed." >&2
    exit 1
fi

if [ $# -eq 0 ]; then
    all
    exit 0
fi

while [ $# -gt 0 ]; do
    if [ ! -d $1 ]; then  
        echo "Error: $1 is not a directory." >&2
        exit 1
    fi
    fixdirs $1
    shift
done
